### PR TITLE
Fix typos discovered by codespell

### PR DESCRIPTION
**Pull request by cclauss**
https://pypi.org/project/codespell

### CODE REVIEW

**Comment by Julien-Elie** [comment]
Thanks for your patch proposal!
Looks good to me; I'll commit it soon.

You should also report the fixes to _m4/libtool.m4_ to the maintainers of the [Libtool package](https://savannah.gnu.org/projects/libtool/) from where the file is taken.

**Comment by cclauss** [comment]
Thanks for your review.  I could revert the changes to `m4/libtool.m4` if that would help.

**Comment by Julien-Elie** [comment]
No need reverting the changes to that specific file; I'll commit them at the same time and ensure your work doesn't get lost when updating it from upstream during the release process.

**Comment by Julien-Elie** [comment]
Merged in 53af3576dd1527dd3e2ab0a101495e00a2532954, thanks!

**Pull request closed without merging**
